CREATE DATABASE CultivoVertical;
USE CultivoVerical;

CREATE TABLE Humedad(
	IdHum INT AUTO_INCREMENT PRIMARY KEY,
    Humedad FLOAT,
    Fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Temperatura(
	IdTemp INT AUTO_INCREMENT PRIMARY KEY,
    Temperatura FLOAT,
    Fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE UltraSonico(
	IdUltra INT AUTO_INCREMENT PRIMARY KEY, 
    nivelAgua FLOAT,
    Fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);